language: node_js
node_js:
- node
deploy:
  provider: npm
  email: Nils_Hirsekorn@online.de
  api_key:
    secure: Ptc47gaZFQyMTJAREi22ljZDVSwDFpVamLEHcdXuGM02mCoxHh9kcs+8Xr+IIsFN6kNOObgqiW+i6Z8ynzdQiBj/g4EacVyaXD/2suEjsE6NNCmT1hDvfhlcPYXWcH7p1UYi3hpkDdqMUGv6gG3Sb/mhAMFmrXlK5d2OX3lhbAl655rEFCfUUDVy08T6E+QtVn52OFG1r7SF1RCo9BgymB9TqlLk5YX+kAcLgIeEbYfu5KFh/rw85SwJYwMmBnGzGESLWD7y+bBeRsUkoatGr3tgaBG43MqpWCsEMhkUvdW7iDvdcNOUej92+Ysil7+QMqHrfKaFTacUjxEk9LNlcHy/fqoh7Xhgk0mfgrvksEpnVWXN+K6FqwHIbVXALvG505y8Q/NfDDAa3RYSuulW3KgRgLoXy2+bvmQN7V+VFDWKuWyysHhMrxpIDI+hT/8eRe9qh1KrIfHyg1s6vr2fDQO1NFHybU8037Ty/zBVG+lus20Kv0mbBxPdD6FuSTeZ2RfLvA0XzA04BrwYrRKqzMfeWDtRNT6rXv4U4KRg85lspEytz0q7MZFNfS/VL8UQWINI59Rt9ZluLPC4p8AxLe4wuPzP8HI0ZjBC2+6KZmas4yQYaFMXb62PmKITjuJag37ivND0uvHc2Nmq5dgkFnn3luppdZZsw43/Rrjrfw8=
  on:
    tags: true
    repo: Kkoile/figure-speaker-update-manager
